/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TreeImport } from './routes/tree'
import { Route as KiosksImport } from './routes/kiosks'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as KiosksIndexImport } from './routes/kiosks/index'
import { Route as KiosksKioskIdImport } from './routes/kiosks/$kioskId'
import { Route as AuthSigninImport } from './routes/auth/signin'

// Create/Update Routes

const TreeRoute = TreeImport.update({
  path: '/tree',
  getParentRoute: () => rootRoute,
} as any)

const KiosksRoute = KiosksImport.update({
  path: '/kiosks',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KiosksIndexRoute = KiosksIndexImport.update({
  path: '/',
  getParentRoute: () => KiosksRoute,
} as any)

const KiosksKioskIdRoute = KiosksKioskIdImport.update({
  path: '/$kioskId',
  getParentRoute: () => KiosksRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/kiosks': {
      preLoaderRoute: typeof KiosksImport
      parentRoute: typeof rootRoute
    }
    '/tree': {
      preLoaderRoute: typeof TreeImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/kiosks/$kioskId': {
      preLoaderRoute: typeof KiosksKioskIdImport
      parentRoute: typeof KiosksImport
    }
    '/kiosks/': {
      preLoaderRoute: typeof KiosksIndexImport
      parentRoute: typeof KiosksImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  KiosksRoute.addChildren([KiosksKioskIdRoute, KiosksIndexRoute]),
  TreeRoute,
  AuthSigninRoute,
])

/* prettier-ignore-end */
